name:                navani
version:             0.1.0.0
github:              "githubuser/navani"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/navani#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- aeson
- raw-strings-qq
- bytestring
- prettyprinter
- servant
# - lucid
- http-media
- http-types
- servant-server
- warp
- type-of-html
- postgresql-simple

library:
  source-dirs: src

executables:
  navani-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - navani

tests:
  navani-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - navani
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-hunit
